AY2223S2-CS2103T-T11-3/tp

- docs/AboutUs.md
Updated roles into AboutUs Page.
> Update AboutUs page to include roles

- docs/team/engenhui1999.md
> Add engenhui1999's PPP

- docs/team/bryansendeavour.md
> Add bryansendeavour's PPP

- docs/UserGuide.md
> Update UG page

- docs/UserGuide.md
> Fix hyperlinks errors by adding new IDs to each header

- docs/team/extrashotlatte.md
> Add Personal Portfolio Page for Sean

- README.md
> Add acknowledgement to original source code

- docs/index.md
> Update Index page

- README.md
Updated CI status badge to correctly point to our repo's.
Contributes to #23
> Update CI status badge to reflect correct repo

- docs/UserGuide.md
- docs/team/bryansendeavour.md
> Remove whitespaces and fix typos

- src/main/java/seedu/address/logic/commands/AddCommand.java
Small error found and fixed in this PR
> Fix message_usage message

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/LinkContactCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/LinkContactCommandParser.java
- src/main/java/seedu/address/logic/parser/NewContactCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/ContactList.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/contact/Contact.java
- src/main/java/seedu/address/model/contact/UniqueContactList.java
- src/main/java/seedu/address/model/person/Event.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/NewContactCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/LinkContactCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Add linkcontact feature 
Contributes to #53
> Linkcontact

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/ui/HelpWindow.java
Removed AB3 traces from HelpWindow file to reflect our product page instead.
Added edit command and linkcontact command to UG and DG and removed listcontact and newrate commands.
> Edit HelpWindow, Update UG and DG

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/testutil/PersonUtil.java
Both start and end time must be indicated to edit timing.
> Allow editing timing

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/MarkCommand.java
> Fix bug for not saving contacts after marking

- src/main/java/seedu/address/logic/parser/LinkContactCommandParser.java
- src/test/java/seedu/address/logic/commands/LinkContactCommandTest.java
- src/test/java/seedu/address/logic/parser/LinkContactCommandParserTest.java
- Shifted `LinkContactCommandTest `to correct package location
- Fixed bug at #92 
- Added more unit test to test `LinkContactCommandParser`
> Fix linkcontact command

- docs/DeveloperGuide.md
- docs/UserGuide.md
- Added `unmark` command into DG and UG.
- Change traces of address book to Paidlancers.
> Add Unmark command into DG and UG.

- src/main/java/seedu/address/logic/commands/RevenueCommand.java
- src/main/java/seedu/address/logic/parser/EventBookParser.java
- src/test/java/seedu/address/logic/commands/RevenueCommandTest.java
- src/test/java/seedu/address/logic/parser/EventBookParserTest.java
> Add new Revenue command to display the total revenue earned

- docs/DeveloperGuide.md
- docs/UserGuide.md
UG: Add Revenue feature into the UG.
DG: Add Mark feature into the implementation and reasons for implementation designs
> Update on UG and DG

- build.gradle
Enabled assertions in build.gradle.
Tested working.
Contributes to #119 .
> Enable assertion for gradle

- src/main/java/seedu/address/MainApp.java
In line with the app release, update main app version to `v.1.2.1`
Closes #134 .
JAR file has been released. Linked [here](https://github.com/AY2223S2-CS2103T-T11-3/tp/releases/tag/v.1.2.1).
> Update app version to v1.2.1

- docs/team/extrashotlatte.md
Updating PPP to reflect things done.
> Update PPP to reflect items done

- src/main/java/seedu/address/model/contact/Contact.java
- src/main/java/seedu/address/model/contact/ContactPhone.java
- src/test/data/JsonSerializableContactListTest/typicalEventsContactList.json
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/contact/ContactPhoneTest.java
- src/test/java/seedu/address/model/contact/ContactTest.java
- src/test/java/seedu/address/testutil/TypicalContacts.java
This PR will solve the following:
- #126 
- Only 8 digit phone numbers will be accepted.
- #123 
- A contact will only be considered as a duplicate if they have the same 8 digit number.
- This exploits the fact that phone numbers are unique.
> Modification in implementation

- docs/DeveloperGuide.md
This PR will
- Correct error spotted
- Change format of implementation to streamline formatting
> Correct some error spotted

- docs/UserGuide.md
Contributes to #112 
Added in User Guide:
- `Clear` command
- `Help` command
- `Find` command
- `Exit` command
While doing this PR I had a few questions in mind:
1. Should we sort the UG in lexicographic order? (Alternatively, we could prioritise a few important commands for the user experience such as the `clear`, `newcontact` and `newevent` command, especially for first time users)
2. Let's include warning for the `clear` command as it is a destructive command that could wipe out the user's data
3. Let's include some form of starting guide in the message area for first time users to look at? For example:
> Update UG to include more commands

- docs/DeveloperGuide.md
- Add 'revenue' feature for the implementation
- Standardised previous implementations
> Update to DG

- src/main/java/seedu/event/MainApp.java
Update version number in MainApp
> Update version number

- docs/UserGuide.md
Add documentation for new event. Closes #220
> Add documentation for Name, Address formats.

- docs/UserGuide.md
- src/main/java/seedu/event/model/contact/ContactPhone.java
- src/test/java/seedu/event/model/contact/ContactPhoneTest.java
This Pr will:
- Fix
-  #223 
-  #187
> Fix the limitations of contact number.

- docs/UserGuide.md
- docs/team/bryansendeavour.md
- docs/team/eksdeeex.md
- docs/team/engenhui1999.md
- src/main/java/seedu/event/commons/util/StringUtil.java
- src/main/java/seedu/event/model/event/NameContainsKeywordsPredicate.java
- src/test/java/seedu/event/commons/util/StringUtilTest.java
- Fixed `find` command bug where program only returns events which full name "matches" the keyword instead of "containing" the keyword
- Contributes to #201
> Fix find command bug

- docs/UserGuide.md
- src/main/java/seedu/event/logic/commands/DeleteCommand.java
- src/main/java/seedu/event/logic/commands/EditCommand.java
- src/main/java/seedu/event/logic/commands/LinkContactCommand.java
- src/main/java/seedu/event/logic/commands/MarkCommand.java
- src/main/java/seedu/event/logic/commands/RemindCommand.java
- src/main/java/seedu/event/logic/commands/UnmarkCommand.java
- Add better clarity to explain that editing of tags will remove all existing tags.
- Add better clarity to safeguard against extreme user inputs beyond unsigned integers.
- Closes #222 
- Closes #182
> Add better clarify in UG

- docs/DeveloperGuide.md
> Add linkcontact planned enhancement

- docs/DeveloperGuide.md
- Added planned enhancements into DG.
- Closes issue:
- #199 
- #202 
- #203 
- #214
> Add planned enhancements into DG

- docs/team/extrashotlatte.md
> Update Sean's PPP

- docs/team/bryansendeavour.md
> Add more contributions and fix some errors
